### PR TITLE
created notebook to plot footprints from new/old ale against ISIS

### PR DESCRIPTION
**Pull request by paarongiroux**
Not sure if this is useful to have here or in the ale repo or neither

### CODE REVIEW

**Comment by krlberry** [comment]
Where is ALE 0.2.0 in the plot? Does it completely line up with the other ALE footprint such that it can't be seen separately?

**Comment by jessemapel** [comment]
One option is to convert the ALE footprints to just points and not lines, or lines with a different wieght.

**Comment by paarongiroux** [comment]
@kberryUSGS ALE 0.2.0 lines up with the ISIS footprint such that it can't be seen

**Comment by paarongiroux** [comment]
Still not too clear but I changed the thicknesses so the the ALE0.2.0 and ISIS footprints can both be seen now

**Comment by krlberry** [comment]
@paarongiroux :+1: I do think it's more clear this way.

**Comment by krlberry** [comment]
And I do think that it's useful to have this notebook here. All the old/initial example notebooks had footprint comparisons and I think that it's a useful comparison to have easily available here. (And your version is cleaner and more automated than the older notebooks since you're using `isis_wkt = str((wkt.loads(GeoDataset(cub_loc).footprint.ExportToWkt())))` instead of requiring the notebook user to copy and paste WKT from the ISIS cube. )

**Review by jessemapel — APPROVED** [review]

**Pull request merged**
