### PR TITLE
Added force flag to anaconda update

### PR DESCRIPTION
**Pull request by jessemapel**
This fixes the error where Anaconda can't update itself during CI.

### CODE REVIEW

**Review by krlberry — APPROVED** [review]
:+1: Looks good to me!

**Comment by jlaura** [comment]
Why are we doing this instead of incrementing the build number? I realize this is easier. I forgot all the time, but do we have another rationale?

**Comment by jessemapel** [comment]
I took this solution from an open issue on the main conda repo: https://github.com/conda/conda/issues/8149

**Comment by jlaura** [comment]
Good answer to a dumb question. update != upload...

**Pull request merged**
