### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jrcain-usgs**
Tested as much as I could with the docs/CI, works up until the AWS credential part (which won't succeed until merged).

### CODE REVIEW

**Comment by Kelvinrr** [comment]
Is there a reason we cant get this working using the instructions for re-using files from the S3 buckets? https://code.chs.usgs.gov/asc/ASC_Software_Docs/-/blob/main/Websites/HOWTO%20-%20Making%20Public%20a%20Site%20Complient.md?ref_type=heads

**Comment by jrcain-usgs** [comment]
Got rid of the _static folder and pointed to the common docs css/scripts instead.

**Comment by Kelvinrr** [comment]
website looks good. 

We just need a readme addition that explains how to build docs and I'll approve this. 

Im assuming it's supposed to be empty? in which case we probably should probably disable pushing to s3 for now

**Comment by jrcain-usgs** [comment]
Added a readme section about building docs, filled in home docs page with stuff from readme, disabled pushing to S3 for now.

**Pull request merged**
