### PR TITLE
added Austin's notebook

### PR DESCRIPTION
**Pull request by Kelvinrr**
100% @AustinSanders  notebook, I just ran it through using my env since he was having env issues and it doesn't look like he will come in before the 11AM deadline.

### CODE REVIEW

**Comment by krlberry** [comment]
Looks like this notebook doesn't have any of the output plots &c? That is, if you have the environment working, could you run the whole notebook, save, and update the PR?

**Comment by Kelvinrr** [comment]
yeah, needed one more push, thanks for catching that.

**Review by krlberry — APPROVED** [review]
:+1:

**Review by AustinSanders — APPROVED** [review]
Looks like the graphs I was getting.  Not that this is good, but it's consistent.

**Comment by Kelvinrr** [comment]
some of the changes that happened the last week must have thrown a wrench into things, but at least this documents the error. 

Once CI passes this should be good to merge.

**Pull request merged**
