### PR TITLE
🚧 [DO NOT MERGE] Update notebooks to reflect linescanner updates to usgscsm 🚧

### PR DESCRIPTION
**Pull request by krlberry**
Don't merge until the below linescan PR for USGSCSM is merged. 

Updates the example notebooks that needed to be updated to either: 

(1) Reflect changes to the isis/csm comparison tables due to the changes to the (unmerged!) linescan code in usgscsm  (see: https://github.com/USGS-Astrogeology/usgscsm/pull/247)

or

(2) Updated os.environ["ISISROOT"] to the standard location of "/usgs/pkgs/isis3.7.0/install"

Notes:
* I did double-check the framers and their values didn't change. 
* I'm seeing a - +/- 0.5 line offset for hirise and lronac that wasn't in the previous iteration of notebooks.
* cassini_isis_nac_cmp is omitted from this PR because I had trouble running it and am not sure I will have time to fix it before I head out for the day.

### CODE REVIEW

**Review by scsides — APPROVED** [review]
This is what was expected. Should we merge these with the usgscsm changes?

**Comment by krlberry** [comment]
Stuart's questions was answered in today's standup. We'll leave this as a "do not merge" until csm work begins again.

**Comment by krlberry** [comment]
I think many further updates have been made to usgscsm since this PR, so it probably makes more sense to close than merge? Perhaps with a ticket to update all the notebooks to reflect the most recent release of usgscsm?

**Comment by jessemapel** [comment]
@kberryUSGS Let's close this and can you add updating our checks to the clean-up work that needs to happen document?

**Pull request closed without merging**
