### PR TITLE
Changed pysis SN to plio

### PR DESCRIPTION
**Pull request by jessemapel**

### CODE REVIEW

**Review by krlberry — APPROVED** [review]
:+1: Very much approve. Thanks for removing the pysis dependency!

**Comment by krlberry** [comment]
Any idea why this is failing on the Mac builds on Travis with `conda: command not found` ? (I restarted it in case the error was temporary)

**Comment by jessemapel** [comment]
Bad download path for conda. I can fix it in a bit.

**Comment by krlberry** [comment]
Is this the same thing that was happening in a lot of the other repos recently?

**Comment by jessemapel** [comment]
yeah

**Pull request merged**
