### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by jlaura**

### CODE REVIEW

**Comment by jlaura** [comment]
This uses the GIT_DESCRIBE _NUMBER because the hashes are not guaranteed to come in in any sortable order. These are.

**Comment by jessemapel** [comment]
is this sufficient or does it need to be part of the version number?

**Comment by jlaura** [comment]
Based on: https://docs.conda.io/projects/conda-build/en/latest/concepts/package-naming-conv.html?highlight=package%20naming 

this should work, but we have this already in `plio` and that is not working. Unfortunately, the plio version is a bit more complicated, so I am not sure if the issue is in the tag or in the GIT_DESCRIBE_NUMBER.

**Comment by jessemapel** [comment]
I'm going to merge this (once CI passes) and then try updating and see what I get.

**Comment by jlaura** [comment]
```bash
➜ conda build recipe --output
/Users/jlaura-pr/miniconda3/conda-bld/osx-64/knoten-0.2.1-py37_0.tar.bz2
```
tested locally

**Comment by jlaura** [comment]
Note: I created a knoten 0.1.0 release so that we have a tag. Without the tag, we have no env variable. Going to look at plio now.

**Comment by jlaura** [comment]
Also, I just updated to pull the extra space in the meta.yaml in the build line, so another round of CI is inbound.

**Pull request merged**
