### PR TITLE
Added Cassini ISS notebook

### PR DESCRIPTION
**Pull request by krlberry**
Added a Cassini ISS demo notebook. This notebook demonstrates how to:
* use the Cassini ISS ALE driver to generate an ISD
* write the ISD to a json file
* instantiate a CSM camera model
* calculate and display an image footprint
* compare this image footprint from ISIS's footprint (though this last steps requires a copy-paste of a WKT string from an ISIS cube) 

New since last update:
* Now added displaying the two images in a stereo pair, plotting their lat/lon extents, and projecting them. 
(borrowed code from @jessemapel's MDIS_Stereo notebook for this)
* Added titles, labels, legend to plots
* Overplotted ISIS and CSM footprints for one image. They are slightly different!

### CODE REVIEW

**Comment by thareUSGS** [comment]
The only additional thing I would like to see is a print of the coords from the CSM footprint (even the first several points). Over-plotting the two might be cool if they are not exact.  Here is an example of plotting two footprints (although stereo). But plotting CSM vs ISIS might be good (unless they are really close -- which is also good to see.  It is nice to see the plot with labels too. https://nbviewer.jupyter.org/urls/gist.githubusercontent.com/jessemapel/baa03c0804f71cc284d8c7ed0bd8695a/raw/6f6ee47e77d597fff978adec3e5d6621e47e9ef8/MDIS_Stereo.ipynb

I am fine as is, so only update if you have time.

**Comment by krlberry** [comment]
Can do!

**Comment by jessemapel** [comment]
Couple comments:

* This is an example notebook, we shouldn't have paths specific to our computers in these.

* You don't need to load the usgscsm library, the knoten init.py file already does it when you import the module.

* The Shapely module isn't in the environment.yml file. We should add it, or create an example environment.yml file.

* You should use the knoten methods to instantiate the camera model instead of the CSM API. See [create_csm](https://github.com/USGS-Astrogeology/knoten/blob/master/knoten/csm.py#L54).

* You should use `with open(...)` when you write out the ISD file.

**Comment by krlberry** [comment]
I made most of the suggested changes but broke the spice locally. Will update here when fixed.

**Comment by krlberry** [comment]
Okay, SPICE fixed and updated! @thareUSGS @jessemapel This is ready for re-review.

**Review by jessemapel — APPROVED** [review]
Looks good to me

**Pull request merged**
